### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chris-martin** [rasputnik/riemannq#2]
Hey, could you please add a license to this project? I'm adding it to a package manager and it'd be nice to not have to mark it as non-free.

**Comment by rasputnik** [comment]
Done, thanks for flagging it up.

What package manager, out of interest?

**Comment by chris-martin** [comment]
Thanks :)

The package manager is [Nix](https://nixos.org/nixpkgs/). I've just added it to [my own config](https://github.com/chris-martin/home/commit/ba41fe71ef55a883c79ceaca6d8aa908193f6199) so far, will submit a PR to [the central package repo](https://github.com/NixOS/nixpkgs) a bit later.
